apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-job-
  annotations:
    argocd.argoproj.io/hook: Sync
    # 那么在资源同步成功完成后，Job 应该会被 Argo CD 自动删除
    argocd.argoproj.io/hook-delete-policy: "HookSucceeded,HookFailed"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: my-container
          image: busybox
          command: [ "/bin/sh", "-c" ]
          args: [ "while true; do date; sleep 1; done" ]